### PR TITLE
exercises/pointer-revocation: make arg volatile

### LINKED ISSUE #20: pointer-revocation exercise shouldn't be compiled with -O2
`ccc` adds `-O2` to the default args, but the pointer revocation demonstration doesn't work quite right with -O2. In particular, the assignment `obj1->arg = (uintptr_t)obj1;` seems to be optimized away by the compiler, though `obj1->fn = fn1;` remains:
```
int
main(void)
{
    struct obj *obj1 = calloc(1, sizeof(*obj1));

    fprintf(stderr, "Installing function pointer in obj1 at %#p\n", obj1);
    obj1->fn = fn1;                  <-- not optimized away
    obj1->arg = (uintptr_t)obj1;     <-- optimized away
```
I can't explain this behavior, but compiling instead with `-O0` produced binaries that behaved as expected.

### PR DESCRIPTION
**Pull request by nwf**
Otherwise the compiler can see that we're only using obj1->arg and so won't
necessarily reload it (and might not even store it) as we wish for
demonstration.

Fixes #20.

### CODE REVIEW

File: src/exercises/pointer-revocation/temporal-control.c [hunk 1]
```diff
@@ -30,7 +30,10 @@ fn2(uintptr_t arg)
 
 struct obj {
 	char buf[32];
-	/* Volatile so that the compiler will always reload it */
+	/*
+	 * The following are volatile so that the compiler will always
+	 * reload them.
+	 */
```
Comment (jrtc27) [inline src/exercises/pointer-revocation/temporal-control.c:36]: Hm, that's not really why we make `arg` volatile, I'm assuming it's more to ensure it's persisted to memory in the first place? I also don't want to give the idea that it needs to be volatile to be revoked.

Comment (brooksdavis) [reply src/exercises/pointer-revocation/temporal-control.c:36]: Hmm, how about
```
	 * The following are volatile so that the compiler will always
	 * store and reload them rather than optimizing memory access
	 * away.
```

Comment (jrtc27) [reply src/exercises/pointer-revocation/temporal-control.c:36]: So, looking at the compiled output, it seems that for RISC-V, the Dead Store Elimination pass optimises out the store into `arg` but leaves the loads in, so they'll see the zeroes from `calloc`. For CHERI-RISC-V it doesn't think the store is dead, which is surprising. Perhaps it doesn't think `void @free(i8 addrspace(200)*)` is the real `free`.

How about something like:
```C
    /*
     * The following are marked volatile to ensure the compiler doesn't
     * constant propagate fn (making aliasing not work) and to ensure neither
     * stores to them are optimised away entirely as dead due to calling free.
     */
```
which is hopefully less vague in a way that makes it clear that it's not a limit of revocation.

**Review by jrtc27 — APPROVED** [review]
